#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Copyright (c) 2026 GE Healthcare
Author: jiheng.zhang@gehealthcare.com
SSO: 212597558

FunASR Keyword Spotting (KWS) Implementation
Generated by Gemini 2.5

This script demonstrates how to use FunASR's KWS models to detect keywords in
audio files and from microphone input in real-time with visualization capabilities.
"""

import os
import sys
import time
import wave
import numpy as np
import argparse
import threading
import queue
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from datetime import datetime

# Attempt to import required packages with helpful error messages
try:
    import pyaudio
except ImportError:
    print("Error: PyAudio is required. Install with: pip install pyaudio")
    print("On Windows, you may need: pip install pipwin && pipwin install pyaudio")
    sys.exit(1)

try:
    import torch
    import torchaudio
except ImportError:
    print("Error: PyTorch and TorchAudio are required.")
    print("Install with: pip install torch torchaudio")
    sys.exit(1)

try:
    from funasr import AutoModel
except ImportError:
    print("Error: FunASR is not installed. Please install with: pip install funasr>=0.8.0")
    print("If you experience issues, see: https://github.com/alibaba-damo-academy/FunASR")
    sys.exit(1)


class KeywordSpottingSystem:
    """
    A comprehensive keyword spotting system using FunASR.
    Generated by Gemini 2.5
    """

    def __init__(self, config=None):
        """Initialize the KWS system with the provided configuration"""
        # Default configuration
        self.config = {
            "model": "damo/speech_fsmn_kws_char_zh-cn-16k-common",
            "device": "cpu",
            "sample_rate": 16000,
            "keywords": ["你好", "开始", "结束", "hello", "start", "stop"],
            "threshold": 0.5,
            "chunk_size": 1600,  # 100ms at 16kHz
            "visualize": False,
            "save_detections": True,
            "output_dir": "output"
        }

        # Update with user configuration if provided
        if config:
            self.config.update(config)

        # Initialize state variables
        self.model = None
        self.audio_interface = None
        self.is_running = False
        self.detection_history = []
        self.audio_buffer = queue.Queue()
        self.audio_data_for_plot = np.zeros(16000)  # 1 second of audio at 16kHz
        self.visualization = None

        # Ensure output directory exists
        if self.config["save_detections"]:
            os.makedirs(self.config["output_dir"], exist_ok=True)

        # Load the KWS model
        self._load_model()

    def _load_model(self):
        """Load the FunASR KWS model"""
        print(f"Loading KWS model: {self.config['model']} on {self.config['device']}...")
        try:
            # Initialize the model with appropriate settings
            self.model = AutoModel(
                model=self.config["model"],
                device=self.config["device"],
                model_type="kws",
                output_format="json",
                disable_update=True
            )
            print("Model loaded successfully!")
        except Exception as e:
            print(f"Error loading model: {e}")
            print("\nTroubleshooting tips:")
            print("1. Check your internet connection")
            print("2. Verify the model name/path is correct")
            print("3. If using GPU, ensure CUDA is properly configured")
            print("4. Try updating FunASR: pip install -U funasr")
            sys.exit(1)

    def process_file(self, file_path):
        """
        Process an audio file and detect keywords

        Args:
            file_path (str): Path to the audio file to process

        Returns:
            list: List of detected keywords with timestamps and confidence scores
        """
        if not os.path.exists(file_path):
            print(f"Error: File not found: {file_path}")
            return []

        print(f"Processing audio file: {file_path}")
        start_time = time.time()

        try:
            # Run inference with the KWS model
            results = self.model(file_path)
            processing_time = time.time() - start_time

            # Format and display results
            detections = self._process_results(results)
            print(f"Processing completed in {processing_time:.2f} seconds")
            print(f"Found {len(detections)} keyword matches")

            # Display detection details
            for detection in detections:
                print(f"Detected '{detection['keyword']}' at {detection['timestamp']:.2f}s "
                      f"(confidence: {detection['confidence']:.2f})")

            return detections

        except Exception as e:
            print(f"Error processing file: {e}")
            return []

    def _process_results(self, results):
        """Process and format the model results"""
        detections = []

        if not results or not isinstance(results, list):
            return detections

        for result in results:
            if not isinstance(result, dict):
                continue

            keyword = result.get('text', '')
            confidence = result.get('score', 0)

            # Only include results above threshold
            if confidence >= self.config["threshold"]:
                timestamp = result.get('timestamp', 0)
                if isinstance(timestamp, list) and len(timestamp) > 0:
                    timestamp = timestamp[0]

                detections.append({
                    'keyword': keyword,
                    'confidence': confidence,
                    'timestamp': timestamp
                })

        return detections

    def start_microphone_detection(self, duration=None):
        """
        Start real-time keyword detection from microphone

        Args:
            duration (int, optional): Duration to listen in seconds, or None for continuous
        """
        # Initialize PyAudio
        self.audio_interface = pyaudio.PyAudio()

        # Show available input devices
        self._list_audio_devices()

        # Initialize visualization if enabled
        if self.config["visualize"]:
            self._setup_visualization()

        # Start processing in a separate thread
        self.is_running = True
        processing_thread = threading.Thread(target=self._microphone_processing_loop, args=(duration,))
        processing_thread.daemon = True
        processing_thread.start()

        try:
            # If visualizing, start the animation loop in the main thread
            if self.config["visualize"]:
                plt.show()
            else:
                # Otherwise just wait for the processing to complete
                print("\nListening for keywords. Press Ctrl+C to stop...")
                while processing_thread.is_alive():
                    time.sleep(0.1)
        except KeyboardInterrupt:
            print("\nStopping...")
        finally:
            self.is_running = False
            self.audio_interface.terminate()
            print("Keyword spotting stopped")

    def _list_audio_devices(self):
        """List available audio input devices"""
        print("\nAvailable audio input devices:")
        info = self.audio_interface.get_host_api_info_by_index(0)
        num_devices = info.get('deviceCount')

        for i in range(num_devices):
            device_info = self.audio_interface.get_device_info_by_host_api_device_index(0, i)
            if device_info.get('maxInputChannels') > 0:
                print(f"  Input Device {i}: {device_info.get('name')}")
        print()

    def _audio_callback(self, in_data, frame_count, time_info, status):
        """PyAudio callback function for real-time processing"""
        # Add the audio data to the queue for processing
        self.audio_buffer.put(in_data)

        # Update the visualization buffer if enabled
        if self.config["visualize"]:
            audio_array = np.frombuffer(in_data, dtype=np.int16).astype(np.float32) / 32768.0
            self.audio_data_for_plot = np.roll(self.audio_data_for_plot, -len(audio_array))
            self.audio_data_for_plot[-len(audio_array):] = audio_array

        return (in_data, pyaudio.paContinue)

    def _microphone_processing_loop(self, duration=None):
        """Main processing loop for microphone input"""
        # Open audio stream
        stream = self.audio_interface.open(
            format=pyaudio.paInt16,
            channels=1,
            rate=self.config["sample_rate"],
            input=True,
            frames_per_buffer=self.config["chunk_size"],
            stream_callback=self._audio_callback
        )

        stream.start_stream()
        start_time = time.time()

        try:
            # Create a temporary directory for audio chunks
            os.makedirs("../temp", exist_ok=True)

            # Main processing loop
            while self.is_running:
                # Check if we've reached the specified duration
                if duration and time.time() - start_time > duration:
                    break

                # Collect audio chunks for processing
                audio_data = b''
                chunks_collected = 0

                # Collect about 1 second of audio
                while chunks_collected < 10 and self.is_running:
                    try:
                        chunk = self.audio_buffer.get(timeout=0.5)
                        audio_data += chunk
                        chunks_collected += 1
                    except queue.Empty:
                        break

                # Process the collected audio
                if audio_data and self.is_running:
                    # Save to temporary file
                    temp_file = os.path.join("../temp", f"kws_temp_{int(time.time() * 1000)}.wav")
                    self._save_audio_to_file(audio_data, temp_file)

                    # Process in a separate thread to avoid blocking the audio callback
                    threading.Thread(
                        target=self._process_audio_chunk,
                        args=(temp_file,)
                    ).start()

                time.sleep(0.1)  # Small delay to reduce CPU usage

        finally:
            if stream.is_active():
                stream.stop_stream()
                stream.close()

    def _process_audio_chunk(self, audio_file):
        """Process an audio chunk file for keyword detection"""
        try:
            results = self.model(audio_file)
            detections = self._process_results(results)

            # Save detections if any found and saving is enabled
            if detections and self.config["save_detections"]:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                for i, detection in enumerate(detections):
                    dest_file = os.path.join(
                        self.config["output_dir"],
                        f"kws_{detection['keyword']}_{timestamp}_{i}.wav"
                    )
                    os.rename(audio_file, dest_file)
                    print(f"Saved detection to {dest_file}")
                    return  # File was renamed, don't try to delete it

            # Clean up temp file if it still exists
            if os.path.exists(audio_file):
                os.remove(audio_file)

        except Exception as e:
            print(f"Error processing audio chunk: {e}")
            # Try to clean up the temp file
            if os.path.exists(audio_file):
                os.remove(audio_file)

    def _save_audio_to_file(self, audio_data, filename):
        """Save raw audio data to a WAV file"""
        try:
            with wave.open(filename, 'wb') as wf:
                wf.setnchannels(1)
                wf.setsampwidth(self.audio_interface.get_sample_size(pyaudio.paInt16))
                wf.setframerate(self.config["sample_rate"])
                wf.writeframes(audio_data)
        except Exception as e:
            print(f"Error saving audio to file: {e}")
            if os.path.exists(filename):
                os.remove(filename)

    def _setup_visualization(self):
        """Set up the real-time audio visualization"""
        plt.figure(figsize=(10, 6))
        plt.subplots_adjust(hspace=0.5)

        # Waveform subplot
        self.ax1 = plt.subplot(2, 1, 1)
        self.line, = self.ax1.plot(np.zeros(1000), '-b')
        self.ax1.set_ylim(-1, 1)
        self.ax1.set_xlim(0, 1000)
        self.ax1.set_title('Real-time Audio Waveform')
        self.ax1.set_ylabel('Amplitude')
        self.ax1.grid(True)

        # Keyword detection history subplot
        self.ax2 = plt.subplot(2, 1, 2)
        self.bars = self.ax2.bar([], [])
        self.ax2.set_title('Detected Keywords')
        self.ax2.set_ylabel('Confidence')
        self.ax2.set_ylim(0, 1.1)

        # Text area for status
        self.status_text = self.ax2.text(0.02, 0.9, "Listening...",
                                         transform=self.ax2.transAxes,
                                         fontsize=12)

        # Create animation
        self.animation = FuncAnimation(
            plt.gcf(), self._update_plot, interval=100, blit=False)

    def _update_plot(self, frame):
        """Update function for the visualization animation"""
        # Update waveform display
        data = self.audio_data_for_plot[-1000:]
        self.line.set_ydata(data)

        # Update keyword history if we have detections
        if self.detection_history:
            labels = [d['keyword'] for d in self.detection_history[-5:]]
            values = [d['confidence'] for d in self.detection_history[-5:]]

            # Update bar chart
            self.ax2.clear()
            self.ax2.bar(labels, values, color='green')
            self.ax2.set_ylim(0, 1.1)
            self.ax2.set_title('Recent Keyword Detections')

            # Update status text
            latest = self.detection_history[-1]
            self.status_text = self.ax2.text(
                0.02, 0.9,
                f"Last detection: {latest['keyword']} ({latest['confidence']:.2f})",
                transform=self.ax2.transAxes, fontsize=12
            )

        return self.line, self.status_text


def main():
    """Main entry point for the script"""
    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description="FunASR Keyword Spotting System (Generated by Gemini 2.5)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument("--file", type=str, default=None,
                        help="Audio file to process (WAV format)")
    parser.add_argument("--model", type=str,
                        default="damo/speech_fsmn_kws_char_zh-cn-16k-common",
                        help="KWS model name or path")
    parser.add_argument("--device", type=str, default="cpu",
                        help="Device to run inference (cpu or cuda:0)")
    parser.add_argument("--keywords", type=str, nargs="+",
                        default=["你好", "开始", "结束", "hello", "start", "stop"],
                        help="Keywords to detect")
    parser.add_argument("--threshold", type=float, default=0.5,
                        help="Detection confidence threshold (0.0-1.0)")
    parser.add_argument("--duration", type=int, default=None,
                        help="Duration to listen in seconds (default: continuous)")
    parser.add_argument("--visualize", action="store_true",
                        help="Enable real-time visualization")
    parser.add_argument("--output", type=str, default="output",
                        help="Directory to save detected keyword audio clips")

    args = parser.parse_args()

    # Print header
    print("\n" + "="*70)
    print("FunASR Keyword Spotting System (Generated by Gemini 2.5)")
    print("="*70)

    # Initialize configuration from command line arguments
    config = {
        "model": args.model,
        "device": args.device,
        "keywords": args.keywords,
        "threshold": args.threshold,
        "visualize": args.visualize,
        "output_dir": args.output
    }

    # Initialize the KWS system
    kws_system = KeywordSpottingSystem(config)

    # Either process a file or start microphone detection
    if args.file:
        kws_system.process_file(args.file)
    else:
        kws_system.start_microphone_detection(duration=args.duration)


if __name__ == "__main__":
    main()
