"""
FunASR Keyword Spotting (KWS) Test Script
-----------------------------------------
This script demonstrates a complete implementation of the FunASR KWS model
for keyword recognition with various features and options.
"""
# generated by Claude Sonnet 3.7
import os
import sys
import time
import argparse
import numpy as np
import soundfile as sf
from datetime import datetime

# Check if funasr is installed
try:
    from funasr import KWS
    from funasr.utils.utils import download_and_extract_file
except ImportError:
    print("Error: FunASR library is not installed.")
    print("Please install it using: pip install funasr")
    sys.exit(1)

class KWSDetector:
    """
    Keyword Spotting Detector using FunASR

    A wrapper class for the FunASR KWS model to provide an easy-to-use
    interface for keyword spotting in audio files or streams.
    """

    def __init__(self, model_path=None, device="cpu", threshold=0.5):
        """
        Initialize the KWS detector

        Args:
            model_path (str): Path to the KWS model (None for default)
            device (str): Device to run inference on ('cpu' or 'cuda')
            threshold (float): Detection threshold (0.0-1.0)
        """
        self.device = device
        self.threshold = threshold
        self.model_path = model_path
        self.model = None
        self.keywords = []

        # Load the model
        self._load_model()

    def _load_model(self):
        """Load the KWS model from FunASR"""
        try:
            print(f"Loading KWS model on {self.device}...")
            start_time = time.time()

            # If model_path is specified, use it, otherwise use the default model
            if self.model_path:
                self.model = KWS(model=self.model_path, device=self.device)
            else:
                self.model = KWS(model="kws-onnx", device=self.device)

            load_time = time.time() - start_time
            print(f"Model loaded successfully in {load_time:.2f} seconds")
        except Exception as e:
            print(f"Failed to load KWS model: {str(e)}")
            sys.exit(1)

    def set_keywords(self, keywords):
        """
        Set the keywords to detect

        Args:
            keywords (list): List of keyword strings to detect
        """
        if not isinstance(keywords, list):
            keywords = [keywords]

        self.keywords = keywords
        print(f"Keywords set for detection: {', '.join(self.keywords)}")

    def detect_from_file(self, audio_path):
        """
        Detect keywords in an audio file

        Args:
            audio_path (str): Path to the audio file

        Returns:
            dict: Detection results
        """
        if not os.path.exists(audio_path):
            print(f"Error: Audio file not found - {audio_path}")
            return None

        if not self.keywords:
            print("Warning: No keywords set for detection")
            return None

        try:
            print(f"Processing file: {audio_path}")
            start_time = time.time()

            # Run inference
            result = self.model(audio_file=audio_path, keywords=self.keywords, threshold=self.threshold)

            process_time = time.time() - start_time
            print(f"Processing completed in {process_time:.2f} seconds")

            return result
        except Exception as e:
            print(f"Error during keyword detection: {str(e)}")
            return None

    def detect_from_array(self, audio_data, sample_rate=16000):
        """
        Detect keywords in an audio array

        Args:
            audio_data (numpy.ndarray): Audio data array
            sample_rate (int): Sample rate of the audio data

        Returns:
            dict: Detection results
        """
        if not isinstance(audio_data, np.ndarray):
            print("Error: Audio data must be a numpy array")
            return None

        if not self.keywords:
            print("Warning: No keywords set for detection")
            return None

        try:
            print(f"Processing audio array (shape: {audio_data.shape}, sr: {sample_rate}Hz)")
            start_time = time.time()

            # Create a temporary file to store the audio data
            temp_file = os.path.join("temp", f"temp_audio_{int(time.time())}.wav")
            os.makedirs(os.path.dirname(temp_file), exist_ok=True)

            # Save the audio data to the temporary file
            sf.write(temp_file, audio_data, sample_rate)

            # Run inference
            result = self.model(audio_file=temp_file, keywords=self.keywords, threshold=self.threshold)

            # Remove the temporary file
            if os.path.exists(temp_file):
                os.remove(temp_file)

            process_time = time.time() - start_time
            print(f"Processing completed in {process_time:.2f} seconds")

            return result
        except Exception as e:
            print(f"Error during keyword detection: {str(e)}")
            return None

    def print_results(self, results):
        """
        Print the detection results in a readable format

        Args:
            results (dict): Detection results from the model
        """
        if not results:
            print("No results to display")
            return

        print("\n=== Keyword Detection Results ===")

        if "detected_keywords" in results:
            detected = results["detected_keywords"]
            if detected:
                print(f"Detected keywords ({len(detected)}):")
                for i, kw in enumerate(detected, 1):
                    print(f"  {i}. {kw}")
            else:
                print("No keywords detected in the audio")

        if "timestamps" in results:
            timestamps = results["timestamps"]
            if timestamps:
                print("\nTimestamps:")
                for kw, times in timestamps.items():
                    for t in times:
                        print(f"  '{kw}' at {t:.2f}s")

        if "confidence_scores" in results:
            scores = results["confidence_scores"]
            if scores:
                print("\nConfidence scores:")
                for kw, score in scores.items():
                    print(f"  '{kw}': {score:.4f}")

        print("===============================\n")


def main():
    """Main function to run the KWS detector"""
    parser = argparse.ArgumentParser(description="FunASR Keyword Spotting Test")
    parser.add_argument("--audio", type=str, default="test.wav",
                        help="Path to the audio file for testing")
    parser.add_argument("--keywords", type=str, nargs="+",
                        default=["hello", "open", "close", "start"],
                        help="Keywords to detect in the audio")
    parser.add_argument("--model", type=str, default=None,
                        help="Path to the KWS model (default: use built-in model)")
    parser.add_argument("--device", type=str, default="cpu",
                        choices=["cpu", "cuda"],
                        help="Device to run inference on (cpu or cuda)")
    parser.add_argument("--threshold", type=float, default=0.5,
                        help="Detection threshold (0.0-1.0)")

    args = parser.parse_args()

    # Print test information
    print("\n" + "="*50)
    print("FunASR Keyword Spotting (KWS) Test")
    print("="*50)
    print(f"Test time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Audio file: {args.audio}")
    print(f"Keywords: {', '.join(args.keywords)}")
    print(f"Device: {args.device}")
    print(f"Threshold: {args.threshold}")
    print("="*50 + "\n")

    # Check if the audio file exists
    if not os.path.exists(args.audio):
        print(f"Error: Audio file not found - {args.audio}")
        print("Please specify a valid audio file with --audio parameter")
        print("Example: python funasr_kws_test1.py --audio path/to/audio.wav")
        return

    # Initialize the KWS detector
    kws_detector = KWSDetector(
        model_path=args.model,
        device=args.device,
        threshold=args.threshold
    )

    # Set the keywords to detect
    kws_detector.set_keywords(args.keywords)

    # Detect keywords in the audio file
    results = kws_detector.detect_from_file(args.audio)

    # Print the results
    kws_detector.print_results(results)

    # Example of using the raw output
    if results:
        print("Raw detection results:")
        print(results)


if __name__ == "__main__":
    main()
