"""
FunASR Keyword Detection Test Script
This script demonstrates how to use FunASR ASR model for keyword detection by 
transcribing audio and searching for keywords in the transcription.
"""
#Generated by ChatGPT 4.1
import os
import sys
import time

try:
    from funasr import AutoModel
except ImportError:
    print("FunASR is not installed. Please install FunASR before running this script.")
    sys.exit(1)

# Path to the audio file for testing
AUDIO_FILE = "test.wav"  # Replace with your test audio file path

# List of keywords to spot (both English and Chinese)
KEYWORDS = ["hello", "open", "close", "start", "开始", "录音", "测试", "现在"]

# Initialize the ASR model for keyword detection
try:
    # Using ASR model for transcription, then we'll search for keywords in the text
    asr_model = AutoModel(model="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", device="cpu")
    print("FunASR ASR model loaded successfully.")
except Exception as e:
    print(f"Failed to load FunASR ASR model: {e}")
    sys.exit(1)

# Run speech recognition and keyword detection
try:
    print(f"Running speech recognition on: {AUDIO_FILE}")
    result = asr_model.generate(input=AUDIO_FILE, cache={}, language="zh")
    print("ASR Result:")
    print(result)
    
    # Extract transcription text
    if result and isinstance(result, list) and len(result) > 0:
        # Handle different result formats
        text_field = result[0].get("text", "")
        if not text_field and "raw_text" in result[0]:
            text_field = result[0]["raw_text"]
        
        transcription = text_field.lower() if text_field else ""
        print(f"\nTranscription: {transcription}")
        
        # Search for keywords in transcription
        detected_keywords = []
        for keyword in KEYWORDS:
            if keyword.lower() in transcription:
                detected_keywords.append(keyword)
        
        print("\nKeyword Detection Results:")
        if detected_keywords:
            print("Detected Keywords:")
            for kw in detected_keywords:
                print(f"- {kw}")
        else:
            print("No keywords detected in the transcription.")
    else:
        print("No transcription available for keyword detection.")
        
except Exception as e:
    print(f"Error during speech recognition: {e}")
    sys.exit(1)

# The keyword detection logic is now integrated above


