"""
FunASR Keyword Detection Test Script
This script demonstrates how to use FunASR ASR model for keyword detection by 
transcribing audio and searching for keywords in the transcription.
"""
#Generated by ChatGPT 4.1
import os
import sys
import time

try:
    from funasr import AutoModel
except ImportError:
    print("FunASR is not installed. Please install FunASR before running this script.")
    sys.exit(1)

# Path to the audio file for testing
AUDIO_FILE = "test.wav"  # Replace with your test audio file path
AUDIO_FILE = "test_hi michael 你好.wav"
AUDIO_FILE = "test_2025-07-21-06-27-17.wav"
# model = "iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
# model = "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch" # ok after remove space " "
# model = "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch" ############################################## GOOD
# model = "damo/speech_fsmn_kws_char_zh-cn-16k-common" # not registered
# model = "iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch" # output is singal word 
model="dengcunqin/speech_seaco_paraformer_large_asr_nat-zh-cantonese-en-16k-common-vocab11666-pytorch" #更换vocab为11666，增加粤语部分字，通过在普通话1w小时、粤语100小时、英语1w小时
# List of keywords to spot (both English and Chinese)Michael
KEYWORDS = ["hello", "open", "close", "start", "开始", "小艾", "测试", "现在","Hi Michael","你好 Michael"]

# Initialize the ASR model for keyword detection
try:
    # Using ASR model for transcription, then we'll search for keywords in the text
    # asr_model = AutoModel(model="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", device="cpu")
    asr_model = AutoModel(model=model, device="cpu")
    # asr_model = AutoModel(model="sanm_kws", device="cpu") # is not ok need namespce
    print("FunASR ASR model loaded successfully.")
except Exception as e:
    print(f"Failed to load FunASR ASR model: {e}")
    sys.exit(1)

# Run speech recognition and keyword detection
try:
    print(f"Running speech recognition on: {AUDIO_FILE}")
    result = asr_model.generate(input=AUDIO_FILE, cache={}, language="zh")
    print("ASR Result:")
    print(result)
    
    # Extract transcription text
    if result and isinstance(result, list) and len(result) > 0:
        # Handle different result formats
        text_field = result[0].get("text", "")
        if not text_field and "raw_text" in result[0]:
            text_field = result[0]["raw_text"]
        
        # Remove spaces from transcription and convert to lowercase
        # transcription = text_field.replace(' ', '').lower() if text_field else ""
        transcription = text_field #keep origina format
        print(f"\nTranscription (spaces removed): {transcription}")
        
        # Search for keywords in transcription
        detected_keywords = []
        for keyword in KEYWORDS:
            if keyword.lower() in transcription:
                detected_keywords.append(keyword)
        
        print("\nKeyword Detection Results:")
        if detected_keywords:
            print("Detected Keywords:")
            for kw in detected_keywords:
                print(f"- {kw}")
        else:
            print("No keywords detected in the transcription.")
    else:
        print("No transcription available for keyword detection.")
        
except Exception as e:
    print(f"Error during speech recognition: {e}")
    sys.exit(1)

# The keyword detection logic is now integrated above


