"""
FunASR Keyword Spotting (KWS) Test Script - Advanced
-----------------------------------------------------
Generated by Gemini 2.5

This script provides a comprehensive test suite for the FunASR KWS model,
including file-based detection, real-time microphone streaming, and detailed result analysis.
"""

import os
import sys
import time
import argparse
import numpy as np
import soundfile as sf
from datetime import datetime

# Check for FunASR installation
try:
    from funasr import KWS
except ImportError:
    print("Error: FunASR library is not installed.")
    print("Please install it using: pip install funasr")
    sys.exit(1)

# Check for sounddevice installation for microphone input
try:
    import sounddevice as sd
except ImportError:
    print("Warning: 'sounddevice' library not found. Microphone streaming will be disabled.")
    print("Install it with: pip install sounddevice")
    sd = None

class KWS_Tester:
    """
    An advanced tester for FunASR Keyword Spotting.

    This class handles model loading, keyword setting, and running KWS on
    both audio files and real-time microphone input.
    """

    def __init__(self, model_id="kws-onnx", device="cpu", threshold=0.5):
        """
        Initializes the KWS_Tester.

        Args:
            model_id (str): The model ID or path for the KWS model.
            device (str): The device to run inference on ('cpu' or 'cuda').
            threshold (float): The detection threshold (0.0 to 1.0).
        """
        self.device = device
        self.threshold = threshold
        self.model_id = model_id
        self.model = None
        self.keywords = []

        self._load_model()

    def _load_model(self):
        """Loads the FunASR KWS model."""
        print(f"Loading KWS model '{self.model_id}' on device '{self.device}'...")
        try:
            start_time = time.time()
            self.model = KWS(model=self.model_id, device=self.device)
            elapsed = time.time() - start_time
            print(f"Model loaded successfully in {elapsed:.2f} seconds.")
        except Exception as e:
            print(f"Fatal: Failed to load KWS model. Error: {e}")
            sys.exit(1)

    def set_keywords(self, keywords):
        """
        Sets the keywords for detection.

        Args:
            keywords (list): A list of keyword strings.
        """
        self.keywords = keywords if isinstance(keywords, list) else [keywords]
        print(f"Keywords for detection have been set to: {', '.join(self.keywords)}")

    def test_from_file(self, audio_path):
        """
        Tests KWS on a given audio file.

        Args:
            audio_path (str): Path to the audio file.

        Returns:
            dict: The detection results from FunASR.
        """
        if not os.path.exists(audio_path):
            print(f"Error: Audio file not found at '{audio_path}'")
            return None

        if not self.keywords:
            print("Warning: No keywords have been set. Detection may not work as expected.")
            return None

        print(f"\n--- Starting File-Based KWS Test ---")
        print(f"Audio File: {audio_path}")

        try:
            start_time = time.time()
            result = self.model(audio_file=audio_path, keywords=self.keywords, threshold=self.threshold)
            elapsed = time.time() - start_time
            print(f"Inference completed in {elapsed:.2f} seconds.")
            return result
        except Exception as e:
            print(f"Error during keyword detection in file: {e}")
            return None

    def test_from_mic(self, duration=10, sample_rate=16000):
        """
        Tests KWS using real-time audio from the microphone.

        Args:
            duration (int): The duration in seconds to record and listen for keywords.
            sample_rate (int): The sample rate for the microphone.
        """
        if not sd:
            print("Error: Microphone streaming is unavailable because 'sounddevice' is not installed.")
            return

        if not self.keywords:
            print("Warning: No keywords have been set. Live detection will not start.")
            return

        print(f"\n--- Starting Live Microphone KWS Test for {duration} seconds ---")
        print(f"Listening for: {', '.join(self.keywords)}...")
        print("Say a keyword into your microphone.")

        try:
            with sd.InputStream(samplerate=sample_rate, channels=1, dtype='int16') as stream:
                for _ in range(int(duration)):
                    audio_chunk, overflowed = stream.read(sample_rate)
                    if overflowed:
                        print("Warning: Audio buffer overflowed!")

                    # Convert to float32, which is expected by some models
                    audio_chunk = audio_chunk.astype(np.float32) / 32768.0

                    # Use a temporary file for processing
                    temp_audio_path = "temp_mic_chunk.wav"
                    sf.write(temp_audio_path, audio_chunk, sample_rate)

                    result = self.model(audio_file=temp_audio_path, keywords=self.keywords, threshold=self.threshold)

                    if result and result.get("detected_keywords"):
                        print(f"  -> Detected: {result['detected_keywords']} at {datetime.now().strftime('%H:%M:%S')}")

                    os.remove(temp_audio_path)
        except Exception as e:
            print(f"An error occurred during microphone streaming: {e}")

        print("--- Live Microphone Test Finished ---")

    @staticmethod
    def display_results(results):
        """
        Prints the detection results in a user-friendly format.

        Args:
            results (dict): The detection results from the model.
        """
        if not results:
            print("\nNo results to display.")
            return

        print("\n=== KWS Detection Results ===")
        detected_kws = results.get("detected_keywords", [])

        if detected_kws:
            print(f"Found {len(detected_kws)} keyword(s):")
            for i, kw in enumerate(detected_kws, 1):
                print(f"  {i}. '{kw}'")
        else:
            print("No keywords were detected in the audio.")

        timestamps = results.get("timestamps")
        if timestamps:
            print("\nTimestamps:")
            for kw, times in timestamps.items():
                time_str = ", ".join([f"{t:.2f}s" for t in times])
                print(f"  - '{kw}' detected at: {time_str}")

        print("=============================\n")

def main():
    """Main function to parse arguments and run the KWS test."""
    parser = argparse.ArgumentParser(
        description="FunASR KWS Test Script (Generated by Gemini 2.5)",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--mode",
        type=str,
        default="file",
        choices=["file", "mic"],
        help="Testing mode:\n"
             "  'file' - Test on a local audio file.\n"
             "  'mic'  - Test using a live microphone stream."
    )
    parser.add_argument(
        "--audio_path",
        type=str,
        default="test.wav",
        help="Path to the audio file to test (for 'file' mode)."
    )
    parser.add_argument(
        "--keywords",
        type=str,
        nargs="+",
        default=["hello", "world"],
        help="A list of keywords to detect."
    )
    parser.add_argument(
        "--model_id",
        type=str,
        default="kws-onnx",
        help="The FunASR model ID or local path to use."
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        choices=["cpu", "cuda"],
        help="The device for model inference."
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="Detection sensitivity threshold (0.0 to 1.0)."
    )
    parser.add_argument(
        "--mic_duration",
        type=int,
        default=10,
        help="Duration in seconds for microphone testing."
    )

    args = parser.parse_args()

    print("="*60)
    print("      FunASR Keyword Spotting (KWS) Advanced Test")
    print("="*60)
    print(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Running in '{args.mode}' mode.")

    # Initialize the KWS tester
    kws_tester = KWS_Tester(
        model_id=args.model_id,
        device=args.device,
        threshold=args.threshold
    )

    # Set keywords
    kws_tester.set_keywords(args.keywords)

    # Run the selected mode
    if args.mode == "file":
        results = kws_tester.test_from_file(args.audio_path)
        kws_tester.display_results(results)
    elif args.mode == "mic":
        kws_tester.test_from_mic(duration=args.mic_duration)

    print("Test script finished.")

if __name__ == "__main__":
    main()

